const strategies = [
  { id:"pe-value", name:"低市盈率选股", category:"long-term", params:[{key:"max_pe",default:15}], execute:(d,p)=>d.filter(s=>s.pe>0&&s.pe<=(p.max_pe||15)).map(s=>({code:s.code,name:s.name,score:80,signals:["低市盈率"],metrics:{pe:s.pe,price:s.price}})) },
  { id:"pb-value", name:"破净选股", category:"long-term", params:[{key:"max_pb",default:1}], execute:(d,p)=>d.filter(s=>s.pb>0&&s.pb<=(p.max_pb||1)).map(s=>({code:s.code,name:s.name,score:85,signals:["破净"],metrics:{pb:s.pb,price:s.price}})) },
  { id:"volume-surge", name:"放量上涨", category:"short-term", params:[{key:"min_volume_ratio",default:1.5}], execute:(d,p)=>d.filter(s=>s.changePct>0&&s.turnover>(p.min_volume_ratio||1.5)).map(s=>({code:s.code,name:s.name,score:75,signals:["放量上涨"],metrics:{turnover:s.turnover,changePct:s.changePct}})) },
  { id:"limit-up", name:"涨停监测", category:"short-term", params:[{key:"min_pct",default:9.5}], execute:(d,p)=>d.filter(s=>s.changePct>=(p.min_pct||9.5)).map(s=>({code:s.code,name:s.name,score:95,signals:["涨停"],metrics:{changePct:s.changePct}})) },
  { id:"high-turnover", name:"换手活跃", category:"short-term", params:[{key:"min_turnover",default:5}], execute:(d,p)=>d.filter(s=>s.turnover>=(p.min_turnover||5)).map(s=>({code:s.code,name:s.name,score:70,signals:["换手活跃"],metrics:{turnover:s.turnover}})) },
  { id:"price-volume", name:"价量齐升", category:"mid-term", params:[{key:"min_pct",default:2},{key:"min_volume_ratio",default:1.5}], execute:(d,p)=>d.filter(s=>s.changePct>(p.min_pct||2)&&s.turnover>(p.min_volume_ratio||1.5)).map(s=>({code:s.code,name:s.name,score:78,signals:["价量齐升"],metrics:{changePct:s.changePct,turnover:s.turnover}})) },
  { id:"deep-rebound", name:"深跌反弹", category:"mid-term", params:[{key:"max_pct",default:-3}], execute:(d,p)=>d.filter(s=>s.changePct<(p.max_pct||-3)).map(s=>({code:s.code,name:s.name,score:72,signals:["深跌反弹机会"],metrics:{changePct:s.changePct}})) },
  { id:"blue-chip", name:"低估蓝筹", category:"long-term", params:[{key:"max_pe",default:15},{key:"min_price",default:10}], execute:(d,p)=>d.filter(s=>s.pe>0&&s.pe<=(p.max_pe||15)&&s.price>=(p.min_price||10)).map(s=>({code:s.code,name:s.name,score:88,signals:["低估蓝筹"],metrics:{pe:s.pe,price:s.price}})) },
  { id:"volume-break", name:"量能突破", category:"short-term", params:[{key:"min_volume",default:100000}], execute:(d,p)=>d.filter(s=>s.volume>=(p.min_volume||100000)).map(s=>({code:s.code,name:s.name,score:76,signals:["量能突破"],metrics:{volume:s.volume}})) },
  { id:"gap-up", name:"跳空高开", category:"short-term", params:[{key:"min_gap",default:1}], execute:(d,p)=>d.filter(s=>s.open>0&&s.price>0&&((s.price-s.open)/s.open*100)>(p.min_gap||1)).map(s=>({code:s.code,name:s.name,score:83,signals:["跳空高开"],metrics:{gap:((s.price-s.open)/s.open*100).toFixed(2)}})) },
  { id:"ma-break", name:"均线突破", category:"mid-term", params:[{key:"ma_period",default:60}], execute:(d,p)=>d.filter(s=>s.changePct>0).map(s=>({code:s.code,name:s.name,score:68,signals:["均线突破"],metrics:{changePct:s.changePct}})) },
  { id:"low-peg", name:"低PEG成长", category:"long-term", params:[{key:"max_pe",default:30}], execute:(d,p)=>d.filter(s=>s.pe>0&&s.pe<=(p.max_pe||30)).map(s=>({code:s.code,name:s.name,score:82,signals:["低PEG成长"],metrics:{pe:s.pe}})) },
  { id:"high-dividend", name:"高股息", category:"long-term", params:[{key:"min_div_yield",default:3}], execute:(d,p)=>d.filter(s=>s.pe>0&&s.pe<=(p.min_div_yield||30)).map(s=>({code:s.code,name:s.name,score:80,signals:["高股息"],metrics:{pe:s.pe}})) },
  { id:"morning-star", name:"早晨之星", category:"short-term", params:[{key:"days",default:3}], execute:(d,p)=>d.filter(s=>s.changePct>0).map(s=>({code:s.code,name:s.name,score:70,signals:["早晨之星"],metrics:{changePct:s.changePct}})) },
  { id:"consecutive-up", name:"连涨股票", category:"short-term", params:[{key:"min_days",default:3}], execute:(d,p)=>d.filter(s=>s.changePct>3).map(s=>({code:s.code,name:s.name,score:77,signals:["连涨"],metrics:{changePct:s.changePct}})) },
  { id:"amplitude", name:"日内振幅选股", category:"day-trade", params:[{key:"min_amplitude",default:5}], execute:(d,p)=>d.filter(s=>s.high&&s.low&&s.close&&((s.high-s.low)/s.close*100)>(p.min_amplitude||5)).map(s=>({code:s.code,name:s.name,score:82,signals:["振幅活跃"],metrics:{amplitude:((s.high-s.low)/s.close*100).toFixed(2)}})) },
];
export default { id:"example-plugin", name:"示例插件", version:"2.0.0", description:"内置策略插件（16策略）", strategies };
